### ISSUE TITLE
[Bug]:  Active Url from Faucet to Browser 

### ISSUE THREAD

**Issue by Zack-Xb** [AvailX/avail-wallet#31]
### Contact Details

None

### What happened?

When navigating to faucet, then navigating to `browser-page` in side menu it remains with `faucet` active in the url.
Similarly when navigating from `brower-page` to the `faucet`, it will remain on the browser dapps menu.

### Version

v0.0.1-alpha

### What operating system are you using?

None

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dev-blc** [comment]
### Issue Resolved

The Faucet page now persists in the same faucet page and does not change to the active page in the embedded browser.

### Fix

Instead of using the same browser instance for both the faucet and the dApp browser, created a new Faucet component that has only the puzzle faucet/dev tools page loaded.

`NOTE - ISSUE WILL BE CLOSED ONCE THE CHANGES ARE FINALISED AND MERGED`
